# Generated by Django 4.2.1 on 2023-05-22 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_form', '0002_userfeedback_sentiment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sentiment',
        ),
    ]
