# Generated by Django 4.2.1 on 2023-05-22 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_form', '0005_delete_sentiment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sentiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentiment_analysis', models.CharField(max_length=50)),
                ('user_sentiment_analysis', models.CharField(max_length=50)),
                ('negative_prob', models.FloatField()),
                ('positive_prob', models.FloatField()),
                ('neutral_prob', models.FloatField()),
                ('true_sentiment', models.CharField(max_length=50)),
                ('sentiment_feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback_form.userfeedback')),
            ],
        ),
    ]
