# Generated by Django 4.2.1 on 2023-05-22 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_form', '0007_alter_sentiment_user_sentiment_analysis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentiment',
            name='true_sentiment',
        ),
    ]
