# Generated by Django 4.2.1 on 2023-05-22 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_form', '0008_remove_sentiment_true_sentiment'),
    ]

    operations = [
        migrations.AddField(
            model_name='userclients',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
