# Generated by Django 4.2.1 on 2023-05-29 00:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feedback_form', '0009_userclients_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='useremployees',
            name='office_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='useremployees',
            name='position',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='useremployees',
            name='office',
            field=models.CharField(max_length=100),
        ),
    ]
