# Generated by Django 4.2.1 on 2023-05-29 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_form', '0010_useremployees_office_user_useremployees_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useremployees',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
